### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by MKuranowski** [vaxerski/Proper-Wordcheck#1]
There are some false positives when using chars out of range [A-Za-z]:
![image](https://user-images.githubusercontent.com/16469272/79864328-96d67380-83d9-11ea-809f-9d50b35e5881.png)

**Comment by vaxerski** [comment]
right, that's an issue.

I'll try to do some unicode in future releases, thanks for the heads-up.

**Comment by vaxerski** [comment]
fixed this particular bug, use 
`allowUnicode(true);`
and it won't happen.

![code](https://i.gyazo.com/b51b1aa3b3ff65a5fde1e268ee7fac05.png)
![output](https://i.gyazo.com/0146885a2410047e05c3ed700ccd3319.png)

I will be working on better and better unicode support and stuff, but since this is fixed, I'm closing this for now.
